version: "2"

run:
  timeout: 15m

linters:
  default: none
  enable:
    - misspell
    - ineffassign

formatters:
  enable:
    - gofmt
    - goimports
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kaito-project/production-stack)
    goimports:
      local-prefixes: github.com/kaito-project/production-stack